version: '2'
services:
  mongodb:
    image: yawei/ubuntu14.04-mongodb:pwd
#    ports:
#      - "27018:27018"
#      - "27019:27019"
#      - "27020:27020"
    network_mode: "host"
#                volumes:
#                        - /data/mongodb : /data/mongodb

  tornado:
    image: yawei/ubuntu14.04-tornado:latest
    depends_on:
      - mongodb
#    ports:
#      - "9100:9100"
#      - "5050:5050"
#      - "5052:5052"
#      - "9700:9700"
    network_mode: "host"
#                volumes:
#                        - /data/server : /data/server
#                        - /data/logs : /data/logs
